      subroutine writcl(iat,ndopx,
     $            iatom,dopant,tag,iptful,fullcl,
     $            versn,vaxflg)
c--------------------------------------------------------------
c  copyright 1993 university of washington         bruce ravel
c--------------------------------------------------------------
      implicit real(a-h,o-z)
      implicit integer(i-n)
c      implicit double precision (a-h,o-z)
c----------------------------------------------------------------
c  write out coords of overfull cell to unit.dat
c----------------------------------------------------------------
c      parameter (iat=50, ndopx=4)
      parameter(iunit=11)

      dimension    iptful(iat), fullcl(iat,192,3)
      character*2  dopant(iatom,ndopx),el
      character*9  versn
      character*8  fname
      character*10 tag(iat)
      logical      vaxflg, there

4000  format(1x,i3,3x,a2,2x,a10,3(3x,f6.3))
4010  format(1x,'! This unit.dat file generated by ATOMS, version '
     $            ,a9)
4020  format(1x,'unit cell')

      fname = 'unit.dat'
      call lower(fname)

      inquire(file=fname, exist=there)
      ii = istrln(fname)
      if (there) then
          call messag(fname(:ii)//' overwritten.')
      else
          call messag('Unit cell written to '//fname(:ii))
      endif

      if (.not.vaxflg) then
          open(unit=iunit,file=fname,status='unknown')
      else
          open(unit=iunit,file=fname,status='new')
      endif

      index = 0
      write(iunit,4010)versn
      write(iunit,4020)
      do 30 i=1,iatom
        do 20 j=1,iptful(i)
          index = index + 1
          el = dopant(i,1)
          call fixsym(el)
          write(iunit,4000)index, el, tag(i), fullcl(i,j,1),
     $                     fullcl(i,j,2), fullcl(i,j,3)
20      continue
30    continue
      close(iunit)

      return
c  end subroutine writcl
      end
